dictionary XYZ{
	float x;
	float y;
	float z;
};

dictionary Cube{
	DOMString name;
	float wx;
	float wy;
	float wz;
};

dictionary Convex{
	DOMString name;
	sequence<XYZ> points;
};

dictionary Sphere{
	DOMString name;
	float radius;
};

dictionary Cylinder{
	DOMString name;
	float radius;
	float height;
};

dictionary Body{
	DOMString shapeName;
	float mass;
	float friction;
	sequence<float> transform;
};

dictionary Scene{
	sequence<Cube> cubes;
	sequence<Convex> convices;
	sequence<Sphere> spheres;
	sequence<Cylinder> cylinders;
	sequence<Body> bodies;
};

dictionary SceneUpdate{
	sequence<float> transform;
	unsigned long long delta;	
};

interface BulletInterface {
	double LoadScene(Scene scene);
	SceneUpdate StepScene(XYZ rayTo, XYZ rayFrom);
	boolean PickObject(double index, XYZ pos, XYZ cpos);
	boolean DropObject();
};