/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "keypairgen.h"

bool_t
xdr_key_pair_t(XDR *xdrs, key_pair_t *objp)
{

	if (!xdr_string(xdrs, &objp->public_key, 500))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->private_key, 500))
		return (FALSE);
	return (TRUE);
}
