dictionary Structure{
    float myValue;
    long myNumber;
};

dictionary ComplicatedStructure {
    float value;
    DOMString name;
    Structure myStructure;
};

partial dictionary ComplicatedStructure{
    float newV;
};

interface MyInterface {
  void myFunction(DOMString myString);
  DOMString myOtherFunction(ComplicatedStructure paramStructure);
};

partial interface MyInterface {
    void forgotThisOne(long myint);
};