/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _KEYPAIRGEN_H_RPCGEN
#define _KEYPAIRGEN_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


struct key_pair_t {
	char *public_key;
	char *private_key;
};
typedef struct key_pair_t key_pair_t;
#ifdef __cplusplus
extern "C" bool_t xdr_key_pair_t(XDR *, key_pair_t*);
#elif __STDC__
extern  bool_t xdr_key_pair_t(XDR *, key_pair_t*);
#else /* Old Style C */
bool_t xdr_key_pair_t();
#endif /* Old Style C */


#define KEYPAIRGEN_PROGRAM ((rpc_uint)80000)
#define KEYPAIRGEN_VERSION ((rpc_uint)0)

#ifdef __cplusplus
#define generate_keypair ((rpc_uint)1)
extern "C" key_pair_t * generate_keypair_0(char **, CLIENT *);
extern "C" key_pair_t * generate_keypair_0_svc(char **, struct svc_req *);

#elif __STDC__
#define generate_keypair ((rpc_uint)1)
extern  key_pair_t * generate_keypair_0(char **, CLIENT *);
extern  key_pair_t * generate_keypair_0_svc(char **, struct svc_req *);

#else /* Old Style C */
#define generate_keypair ((rpc_uint)1)
extern  key_pair_t * generate_keypair_0();
extern  key_pair_t * generate_keypair_0_svc();
#endif /* Old Style C */

#endif /* !_KEYPAIRGEN_H_RPCGEN */
