
all: .PHONY

.PHONY: project_code

project_code:
	$(MAKE) -C Logger
	$(MAKE) -C Fib
	$(MAKE) -C ObjectsExample


clean:
	$(MAKE) -C Logger clean
	$(MAKE) -C Fib clean
	$(MAKE) -C ObjectsExample clean